version: '3.4'

services:
  faksuefrontend:
    image: faksuefrontend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 80:5173
